package Circuit_De_Stage.Backend.Entities.Enum;

public enum DocumentType {
    CV,
    LETTRE_DE_MOTIVATION,
    DEMANDE_DE_STAGE,
    DEMANDE_DE_STAGE_SINGER,
    
    CLASSEMENT,

    BULLETIN_DE_MOUVEMENT_REMPLIE, 
    BULLETIN_DE_MOUVEMENT_VIDE, 
        
    CONVOCATION,
    CONVOCATION_SIGNER,

    LAISSER_PASSER, 
    PRISE_DE_SERVICE,
    
    RAPPORT,
    RAPPORT_SIGNE,

    ATTESTATION
}
