export enum DocumentType {
    CV = 'CV',
    LETTRE_DE_MOTIVATION = 'LETTRE_DE_MOTIVATION',
    DEMANDE_DE_STAGE = 'DEMANDE_DE_STAGE',
    DEMANDE_DE_STAGE_SINGER = 'DEMANDE_DE_STAGE_SINGER',
    CLASSEMENT = 'CLASSEMENT',
    BULLETIN_DE_MOUVEMENT_REMPLIE = 'BULLETIN_DE_MOUVEMENT_REMPLIE',
    BULLETIN_DE_MOUVEMENT_VIDE = 'BULLETIN_DE_MOUVEMENT_VIDE',
    CONVOCATION = 'CONVOCATION',
    CONVOCATION_SIGNER = 'CONVOCATION_SIGNER',
    LAISSER_PASSER = 'LAISSER_PASSER',
    RAPPORT = 'RAPPORT',
    ATTESTATION = 'ATTESTATION'
}