export enum RoleType {
    STAGIAIRE = 'STAGIAIRE',
    ENCADRANT = 'ENCADRANT',
    DCRH = 'DCRH',
    SERVICE_ADMINISTRATIVE = 'SERVICE_ADMINISTRATIVE',
    CENTRE_DE_FORMATION = 'CENTRE_DE_FORMATION'
}